/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Beans.IngredientBean;
import Beans.RawBean;
import DAO.Implementation.RawDAOImplementation;
import DAO.Interface.RawDAOInterface;
import java.awt.Component;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author earleenjanefuentes
 */
public class addIngredient extends javax.swing.JFrame {

    private RawDAOInterface rwImp = new RawDAOImplementation();
    private AddRecipe ar;
    private EditRecipe rcm;
    private ArrayList<IngredientBean> ai;

    /**
     * Creates new form addIngredient
     */
    public addIngredient() {
        initComponents();
        prepareTable();
    }

    public addIngredient(AddRecipe a, ArrayList<IngredientBean> i, String r) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        String laf = UIManager.getSystemLookAndFeelClassName();
        UIManager.setLookAndFeel(laf);
        initComponents();
        errorLabel.setVisible(false);
        errorLabel1.setVisible(false);
        this.ar = a;
        this.ai = i;
        prepareTable();
        recipeLabel.setText(r);
        //System.out.println("Opened from addrecipe");
    }

    public addIngredient(EditRecipe r, ArrayList<IngredientBean> i, String rn) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        String laf = UIManager.getSystemLookAndFeelClassName();
        UIManager.setLookAndFeel(laf);
        initComponents();
        errorLabel.setVisible(false);
        errorLabel1.setVisible(false);
        this.rcm = r;
        this.ai = i;
        prepareTable();
        recipeLabel.setText(rn);
       // System.out.println("Opened from rcmanagement");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ingredientTable = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        rawTable = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        addRaw = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        quantityField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        editField = new javax.swing.JTextField();
        editQuantity = new javax.swing.JButton();
        deleteIngredient = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        errorLabel1 = new javax.swing.JLabel();
        recipeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ingredientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ingredientTable);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Ingredients");

        rawTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(rawTable);

        addRaw.setText("Add");
        addRaw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRawActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantity: ");

        quantityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Edit quantity: ");

        editField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFieldActionPerformed(evt);
            }
        });

        editQuantity.setText("Edit");
        editQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editQuantityActionPerformed(evt);
            }
        });

        deleteIngredient.setText("Remove");
        deleteIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteIngredientActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Back");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Raw Material:");

        jLabel5.setText("Ingredients");

        errorLabel.setForeground(new java.awt.Color(204, 0, 51));
        errorLabel.setText("ERROR: Please enter valid number");

        errorLabel1.setForeground(new java.awt.Color(204, 0, 51));
        errorLabel1.setText("ERROR: Please enter valid number");

        recipeLabel.setForeground(new java.awt.Color(204, 0, 51));
        recipeLabel.setText("Recipe Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addRaw))
                            .addComponent(errorLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editQuantity)
                                .addGap(18, 18, 18)
                                .addComponent(deleteIngredient))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(errorLabel1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(recipeLabel)
                        .addGap(25, 25, 25))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(406, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(recipeLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteIngredient)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addRaw)
                        .addComponent(jLabel3)
                        .addComponent(editField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editQuantity)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorLabel)
                    .addComponent(errorLabel1))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addGap(11, 11, 11))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(121, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editFieldActionPerformed

    private void quantityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
        if (ar != null) {
            ar.setVisible(true);
        } else {
            rcm.setVisible(true);
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void addRawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRawActionPerformed
        String quantity = quantityField.getText().toString();
        if (rawTable.getSelectedRow() < 0) {
            return;
        }
        if (isNumber(quantity) && Float.parseFloat(quantity) > 0) {
            int rselect = rawTable.getSelectedRow();
            addIngredient(rselect, Float.parseFloat(quantity));
            quantityField.setText("");
            errorLabel.setVisible(false);
        } else {
            errorLabel.setVisible(true);
        }
    }//GEN-LAST:event_addRawActionPerformed

    private void deleteIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteIngredientActionPerformed
        int rselect = ingredientTable.getSelectedRow();
        if (rselect < 0) {
            return;
        } else {
            deleteIngredient(rselect);
        }

    }//GEN-LAST:event_deleteIngredientActionPerformed

    private void editQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editQuantityActionPerformed
        String quantity = editField.getText().toString();
        if (ingredientTable.getSelectedRow() < 0) {
            return;
        }
        if (isNumber(quantity) && Float.parseFloat(quantity) > 0) {
            int rselect = ingredientTable.getSelectedRow();
            editQuantity(rselect, Float.parseFloat(quantity));
            errorLabel1.setVisible(false);
        } else {
            errorLabel1.setVisible(true);
        }
    }//GEN-LAST:event_editQuantityActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        int nrow = ingredientTable.getRowCount();
        
        //System.out.println(nrow);
        int i;
        int rid;

        ai.clear();
        for (i = 0; i < nrow; i++) {
            IngredientBean ibean = new IngredientBean();
            RawBean rbean = new RawBean();

            rid = Integer.parseInt(ingredientTable.getModel().getValueAt(i, 0).toString());
            rbean = rwImp.getRaw(rid);
            ibean.setRaw(rbean);
            ibean.setAmount(Float.parseFloat(ingredientTable.getModel().getValueAt(i, 2).toString()));
            ai.add(ibean);
        }

        this.setVisible(false);
        if (ar != null) {
            ar.setVisible(true);
            ar.prepareCombo();
            ar.computeActual();
            if(nrow == 0){
                ar.inErrorV(true);
            }else{
                ar.inErrorV(false);
            }
        } else {
            rcm.setVisible(true);
            rcm.reloadIngredients(ai);
            rcm.computeActual(ai);
            if(nrow == 0){
                rcm.inErrorV(true);
            }else{
                rcm.inErrorV(false);
            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * * <--- JANERYS CODE STARTS HERE ---> **
     */
    //edit quantity
    private void editQuantity(int r, float q) {
        ingredientTable.getModel().setValueAt(q, r, 2);
    }

    //add Ingredient
    private void addIngredient(int r, float q) {
        int rID = Integer.parseInt(rawTable.getModel().getValueAt(r, 0).toString());
        RawBean rm = rwImp.getRaw(rID);

        Object[] ingredient = {rm.getRawID(), rm.getRaw(), String.format("%.2f", q), rm.getUom(), String.format("%.2f", rm.getPrice()*q)};

        TableModel model = rawTable.getModel();
        TableModel inmodel = ingredientTable.getModel();
        DefaultTableModel imodel = (DefaultTableModel) model;
        DefaultTableModel ingmodel = (DefaultTableModel) inmodel;
        //add to ingredientTable
        ingmodel.addRow(ingredient);
        ingredientTable.setModel(ingmodel);
        //remove from rawTable
        imodel.removeRow(r);
        rawTable.setModel(imodel);

    }

    //delete ingredient
    private void deleteIngredient(int r) {
        int rID = Integer.parseInt(ingredientTable.getModel().getValueAt(r, 0).toString());
        RawBean rm = rwImp.getRaw(rID);

        Object[] raw = {rm.getRawID(), rm.getRaw()};

        TableModel model = rawTable.getModel();
        TableModel imodel = ingredientTable.getModel();
        DefaultTableModel rmodel = (DefaultTableModel) model;
        DefaultTableModel ingmodel = (DefaultTableModel) imodel;

        //add to rawTable
        rmodel.addRow(raw);
        rawTable.setModel(rmodel);
        //remove from ingredientTable
        ingmodel.removeRow(r);
        ingredientTable.setModel(ingmodel);
    }

    //check if number
    private boolean isNumber(String s) {
        try {
            Float.parseFloat(s);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    //prepare rawTable
    private void prepareTable() {
        String cols[] = {"Raw ID", "Raw Material", "UOM", "Price"};
        ArrayList<RawBean> avRaw = rwImp.getRawByStatus("available");
        DefaultTableModel rawModel = new DefaultTableModel(cols, 0);
        
        for (RawBean rm : avRaw) {
            Object[] raw = {rm.getRawID(), rm.getRaw(), rm.getUom(), String.format("%.2f", rm.getPrice())};
            boolean skip = false;
            for (IngredientBean ibean2 : ai) {
                if (rm.getRawID() == ibean2.getRaw().getRawID()) {
                    skip = true;
                    break;
                }
            }
            if (!skip) {
                rawModel.addRow(raw);
            }
        }

        rawTable.setModel(rawModel);
        rawTable.getColumnModel().getColumn(0).setMinWidth(0);
        rawTable.getColumnModel().getColumn(0).setMaxWidth(0);
        adjustTable(rawTable);

        //ingredient Tab
        String cols2[] = {"Raw ID", "Raw Material", "Quantity", "UOM", "Total Price"};
        DefaultTableModel ingredientModel = new DefaultTableModel(cols2, 0);
        
        for (IngredientBean ibean : ai) {
            Object[] ingredient = {ibean.getRaw().getRawID(), ibean.getRaw().getRaw(), String.format("%.2f", ibean.getAmount()), ibean.getRaw().getUom(), String.format("%.2f", ibean.getRaw().getPrice()*ibean.getAmount())};
            ingredientModel.addRow(ingredient);
        }
        ingredientTable.setModel(ingredientModel);
        ingredientTable.getColumnModel().getColumn(0).setMinWidth(0);
        ingredientTable.getColumnModel().getColumn(0).setMaxWidth(0);
        adjustTable(ingredientTable);
    }

    /* ADJUST TABLE TO MAX WIDTH*/
    private void adjustTable(JTable table) {
        for (int column = 0; column < table.getColumnCount(); column++) {
            TableColumn tableColumn = table.getColumnModel().getColumn(column);
            int preferredWidth = tableColumn.getMinWidth();
            int maxWidth = tableColumn.getMaxWidth();

            for (int row = 0; row < table.getRowCount(); row++) {
                TableCellRenderer cellRenderer = table.getCellRenderer(row, column);
                Component c = table.prepareRenderer(cellRenderer, row, column);
                int width = c.getPreferredSize().width + table.getIntercellSpacing().width;
                preferredWidth = Math.max(preferredWidth, width);

                //  We've exceeded the maximum width, no need to check other rows
                if (preferredWidth >= maxWidth) {
                    preferredWidth = maxWidth;
                    break;
                }
            }

            tableColumn.setPreferredWidth(preferredWidth);
        }
    }
    

    /**
     * * <--- JANERYS CODE ENDS HERE ---> **
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRaw;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deleteIngredient;
    private javax.swing.JTextField editField;
    private javax.swing.JButton editQuantity;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel errorLabel1;
    private javax.swing.JTable ingredientTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField quantityField;
    private javax.swing.JTable rawTable;
    private javax.swing.JLabel recipeLabel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
