package UI;

import Beans.IngredientBean;
import Beans.RawBean;
import Beans.RecipeBean;
import DAO.Implementation.IngredientDAOImplementation;
import DAO.Implementation.RawDAOImplementation;
import DAO.Implementation.RecipeDAOImplementation;
import DAO.Interface.IngredientDAOInterface;
import DAO.Interface.RawDAOInterface;
import DAO.Interface.RecipeDAOInterface;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Evy
 */
public class EODTab extends javax.swing.JFrame {

    RecipeDAOInterface rcImp = new RecipeDAOImplementation();
    IngredientDAOInterface inImp = new IngredientDAOImplementation();
    RawDAOInterface rwImp = new RawDAOImplementation();
  

    /**
     * Creates new form EODTab
     */
    public EODTab() throws ClassNotFoundException, InstantiationException, UnsupportedLookAndFeelException, IllegalAccessException {

        String laf = UIManager.getSystemLookAndFeelClassName();
        UIManager.setLookAndFeel(laf);
        initComponents();
        prepareTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        notificationTable = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        jLabel3 = new javax.swing.JLabel();
        InventoryTab = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        recipeTable = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        jScrollPane1 = new javax.swing.JScrollPane();
        rawTable = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rcMgt = new javax.swing.JButton();
        rmMgt1 = new javax.swing.JButton();
        cMgt2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        salesBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        actualBtn = new javax.swing.JButton();
        UTWbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        notificationTable.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        notificationTable.setForeground(new java.awt.Color(255, 51, 51));
        notificationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(notificationTable);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(663, 85, 256, 444);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("LOW SUPPLY NOTIFICATION");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(663, 50, 253, 24);

        jPanel5.setOpaque(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, InventoryTab, org.jdesktop.beansbinding.ObjectProperty.create(), jPanel5, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        jPanel5.setLayout(null);

        recipeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(recipeTable);

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(160, 50, 452, 160);

        rawTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(rawTable);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(160, 270, 452, 170);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("RECIPE STOCK");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(167, 16, 179, 32);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setText("RAW MATERIAL STOCK");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(170, 230, 279, 32);

        rcMgt.setText("Recipe Management");
        rcMgt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcMgtActionPerformed(evt);
            }
        });
        jPanel5.add(rcMgt);
        rcMgt.setBounds(0, 40, 160, 50);

        rmMgt1.setText("Manage Raw Materials");
        rmMgt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmMgt1ActionPerformed(evt);
            }
        });
        jPanel5.add(rmMgt1);
        rmMgt1.setBounds(0, 130, 160, 50);

        cMgt2.setText("Category Management");
        cMgt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cMgt2ActionPerformed(evt);
            }
        });
        jPanel5.add(cMgt2);
        cMgt2.setBounds(0, 220, 160, 50);

        jLabel4.setBackground(new java.awt.Color(51, 204, 255));
        jLabel4.setOpaque(true);
        jPanel5.add(jLabel4);
        jLabel4.setBounds(0, 0, 160, 500);

        InventoryTab.addTab("INVENTORY", jPanel5);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(null);

        salesBtn.setText("SALES");
        salesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesBtnActionPerformed(evt);
            }
        });
        jPanel6.add(salesBtn);
        salesBtn.setBounds(0, 220, 160, 50);

        jButton2.setText("DELIVERY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);
        jButton2.setBounds(0, 40, 160, 50);

        actualBtn.setText("INPUT RAW MATERIAL COUNT");
        actualBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualBtnActionPerformed(evt);
            }
        });
        jPanel6.add(actualBtn);
        actualBtn.setBounds(0, 130, 160, 50);

        UTWbtn.setText("USED/TRANSFERED AND WASTAGES");
        UTWbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UTWbtnActionPerformed(evt);
            }
        });
        jPanel6.add(UTWbtn);
        UTWbtn.setBounds(0, 310, 160, 50);

        jLabel6.setBackground(new java.awt.Color(51, 204, 255));
        jLabel6.setOpaque(true);
        jPanel6.add(jLabel6);
        jLabel6.setBounds(0, 0, 160, 500);

        InventoryTab.addTab("EOD", jPanel6);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jButton7.setText("Expenses");
        jPanel3.add(jButton7);
        jButton7.setBounds(0, 40, 160, 50);

        jButton8.setText("Gross Income");
        jPanel3.add(jButton8);
        jButton8.setBounds(0, 130, 160, 50);

        jButton9.setText("Net Income");
        jPanel3.add(jButton9);
        jButton9.setBounds(0, 220, 160, 50);

        jButton10.setText("EXPORT");
        jPanel3.add(jButton10);
        jButton10.setBounds(0, 400, 160, 50);

        jButton1.setText("Variance");
        jPanel3.add(jButton1);
        jButton1.setBounds(0, 310, 160, 50);

        jLabel5.setBackground(new java.awt.Color(51, 204, 255));
        jLabel5.setOpaque(true);
        jPanel3.add(jLabel5);
        jLabel5.setBounds(0, 0, 160, 500);

        InventoryTab.addTab("REPORT", jPanel3);

        jPanel1.add(InventoryTab);
        InventoryTab.setBounds(0, 70, 635, 480);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Background.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 960, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        // DELIVERY
        this.setVisible(false);
        try {
            DELIVERY deliveryWindow = new DELIVERY(this);
            deliveryWindow.setVisible(true);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void salesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesBtnActionPerformed
        this.setVisible(false);
        try {
            SALES saleswindow = new SALES(this);
            saleswindow.setVisible(true);
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_salesBtnActionPerformed

    private void rcMgtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcMgtActionPerformed
        this.setVisible(false);
        try {
            RCManagement rcmgt = new RCManagement();
            rcmgt.setVisible(true);
        } catch (Exception e) {
            System.out.println(e);
        }
        
        dispose();
    }//GEN-LAST:event_rcMgtActionPerformed

    private void rmMgt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmMgt1ActionPerformed
        try {
            RMManagement rm = new RMManagement();
            rm.setVisible(true);
            dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EODTab.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(EODTab.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(EODTab.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(EODTab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rmMgt1ActionPerformed

    private void cMgt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cMgt2ActionPerformed
        try {
            CategoryManagement ct = new CategoryManagement();
            ct.setVisible(true);
            dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EODTab.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(EODTab.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(EODTab.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(EODTab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cMgt2ActionPerformed

    private void UTWbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UTWbtnActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        try {
            UsedTransfer usedWindow = new UsedTransfer(this);
            usedWindow.setVisible(true);
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_UTWbtnActionPerformed

    private void actualBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualBtnActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        try {
            ACTUALINPUT actualWindow = new ACTUALINPUT(this);
            actualWindow.setVisible(true);
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_actualBtnActionPerformed

    /**
     * < -- JANERYS FUNCTIONS START -- > *
     */
    /* Prepare Table */
    private void prepareTable() {

        ArrayList<RecipeBean> avRecipes = new ArrayList<RecipeBean>();
        ArrayList<RawBean> avRaw = new ArrayList<RawBean>();
        int i, j;

        // recipe Stocks
        String cols[] = {"Name", "Stock"};
        DefaultTableModel recipeModel = new DefaultTableModel(cols, 0);
        avRecipes = rcImp.getRecipeByStatus("available");

        if (avRecipes != null) {
            for (i = 0; i < avRecipes.size(); i++) {
                RecipeBean rc = avRecipes.get(i);
                ArrayList<IngredientBean> ingredients = new ArrayList<IngredientBean>();
                ingredients = rc.getIngredients();

                Object[] rec = {"<html><p style = 'color:red'><b>" + rc.getRecipe() + "</b></p></html>", "<html><p style = 'color:red'><b>" + String.format("%.2f", rc.computeStock()) + "</b></p></html>"};
                recipeModel.addRow(rec);

                for (j = 0; j < ingredients.size(); j++) {
                    RawBean raw = ingredients.get(j).getRaw();
                    Object[] rawm = {"     " + ingredients.get(j).getAmount() + " " + raw.getUom() + " of " + raw.getRaw(), String.format("%.2f", raw.getStock())};
                    recipeModel.addRow(rawm);
                }
            }
        }

        recipeTable.setModel(recipeModel);

        // raw material stock
        DefaultTableModel rawModel = new DefaultTableModel(cols, 0);
        DefaultTableModel notificationModel = new DefaultTableModel(cols, 0);
        avRaw = rwImp.getRawByStatus("available");

        if (avRaw != null) {
            for (i = 0; i < avRaw.size(); i++) {
                RawBean rm = avRaw.get(i);
                Object[] raw = {rm.getRaw(), String.format("%.2f", rm.getStock())};
                if (rm.isCritical()) {
                    notificationModel.addRow(raw);
                }
                rawModel.addRow(raw);
            }
        }

        rawTable.setModel(rawModel);
        notificationTable.setModel(notificationModel);
        
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(DefaultTableCellRenderer.RIGHT);
        notificationTable.getColumn("Stock").setCellRenderer(rightRenderer);
        rawTable.getColumn("Stock").setCellRenderer(rightRenderer);
        recipeTable.getColumn("Stock").setCellRenderer(rightRenderer);
        recipeTable.setRowSelectionAllowed(true);
        //System.out.println(recipeTable.getRowSelectionAllowed());
    }

    /**
     * < -- JANERYS FUNCTIONS END -- > *
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EODTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EODTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EODTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EODTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EODTab().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(EODTab.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(EODTab.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(EODTab.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(EODTab.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane InventoryTab;
    private javax.swing.JButton UTWbtn;
    private javax.swing.JButton actualBtn;
    private javax.swing.JButton cMgt2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable notificationTable;
    private javax.swing.JTable rawTable;
    private javax.swing.JButton rcMgt;
    private javax.swing.JTable recipeTable;
    private javax.swing.JButton rmMgt1;
    private javax.swing.JButton salesBtn;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
